# Generated by Django 3.2.4 on 2021-07-19 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(max_length=20, verbose_name='Siglas')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=60, verbose_name='Dirección de la casa')),
                ('val_bien', models.FloatField(verbose_name='Valor del bien')),
                ('num_cuartos', models.IntegerField(verbose_name='Número de cuartos')),
                ('val_mensual', models.FloatField(verbose_name='Valor mensual de mantenimiento')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrioDept', to='administrativo.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaDept', to='administrativo.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=60, verbose_name='Dirección de la casa')),
                ('val_bien', models.FloatField(verbose_name='Valor del bien')),
                ('color', models.CharField(max_length=20, verbose_name='Color del Inmueble')),
                ('num_cuartos', models.IntegerField(verbose_name='Número de cuartos')),
                ('num_pisos', models.IntegerField(verbose_name='Número de pisos')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrioCasa', to='administrativo.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaCasa', to='administrativo.persona')),
            ],
        ),
    ]
