# Generated by Django 3.2.4 on 2021-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(default='null', max_length=50, verbose_name='Nombre del barrio'),
            preserve_default=False,
        ),
    ]
